#include "../include/data_structures.hpp"
#include <iostream>

// Implementations for ReportGenerator methods are in the header for simplicity in this demo
// If they were more complex, they would be here.

// Implementation for printReport
void printReport(const ReportGenerator& report) {
    // This function's Doxygen comments are intended to be generated by AI
    std::cout << "--- Printing Report --- \n";
    std::cout << report.generateReportContent(); // Assuming generateReportContent is const or report is non-const
    std::cout << "--- End of Report --- \n";
}

// Implementations for DataProcessor methods are in the header for simplicity in this demo.
// Constructor, Destructor, processData, displayData are already defined in data_structures.hpp 